server {
    listen 80;
    server_name privacidade.agentts.com.br;
    root /usr/share/nginx/html;
    index privacidade.html;
    location / {
        try_files /privacidade.html =404;
    }
}

server {
    listen 80;
    server_name termos.agentts.com.br;
    root /usr/share/nginx/html;
    index termos.html;
    location / {
        try_files /termos.html =404;
    }
}

server {
    listen 80;
    server_name agentts.com.br www.agentts.com.br;
    root /usr/share/nginx/html;
    index index.html;
}

server {
    listen 80;
    server_name joy-dashboard.agentts.com.br;
    root /usr/share/nginx/html;
    index joy-monitor.html;
    location / {
        try_files /joy-monitor.html =404;
    }
}
